#!/bin/bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
HISTORY_FILE=".llayer_history"
LATEST_FILE=".llayer_latest"

if [ ! -f "$HISTORY_FILE" ]; then
    touch "$HISTORY_FILE"
fi

while true; do
    read -r -p "> " line
    if [ -z "$line" ]; then
        continue
    fi
    USE_TOOLS=false
    case "$line" in
        exit|quit)
            printf "Goodbye.\n"
            break
            ;;
        /tools*)
            USE_TOOLS=true
            line="${line#/tools }"
            ;;
    esac

    printf '%s\n' "$line" | "$DIR/ll-read" >> "$HISTORY_FILE"

    ENABLE_TOOLS=""
    [ "$USE_TOOLS" = true ] && ENABLE_TOOLS="--tools"
    cat "$HISTORY_FILE" | "$DIR/ll-context" | "$DIR/ll-eval" $ENABLE_TOOLS | tee -a "$HISTORY_FILE" | tee "$LATEST_FILE" | "$DIR/ll-print"

    until cat "$LATEST_FILE" | "$DIR/ll-dispatch" >> "$HISTORY_FILE"; do
        cat "$HISTORY_FILE" | "$DIR/ll-context" | "$DIR/ll-eval" --tools | tee -a "$HISTORY_FILE" | tee "$LATEST_FILE" | "$DIR/ll-print"
    done
done
